# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on: [workflow_dispatch]

env:
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  E2E_BASE_URL: ${{ secrets.E2E_BASE_URL }}
  E2E_SERVER_BASE_URL: ${{ secrets.E2E_SERVER_BASE_URL }}
  E2E_USER_NAME: ${{ secrets.E2E_USER_NAME }}
  E2E_PASSWORD: ${{ secrets.E2E_PASSWORD }}
  E2E_ENCRYPTION_PASSWORD: ${{ secrets.E2E_ENCRYPTION_PASSWORD }}

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest python-dotenv
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install build
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build version and install package
      run: |
        python -m build
        python -m pip install dist/dracoon-${{ secrets.VERSION }}.tar.gz
    - name: Test client
      run: |
        python tests/test_client.py
